---

- name: chat.erethon.com xmpp docker
  docker:
    name: chat.erethon.com
    image: prosody/prosody
    state: restarted
    restart_policy: always
    pull: always
    ports:
    - 5222:5222
    - 5269:5269
    volumes:
    - /data/volumes/prosody/etc:/etc/prosody:ro
    - /data/volumes/prosody/data:/var/lib/prosody
