---

ferm__host_rules:
  - type: 'accept'
    filename: 'haproxy'
    name: 'haproxy'
    table: 'filter'
    chain: 'INPUT'
    dport: [ 80, 443 ]
    protocol: 'tcp'
    domain: 'ip'

  - type: 'accept'
    filename: 'openvpn'
    name: 'openvpn'
    table: 'filter'
    chain: 'INPUT'
    dport: [ 1194 ]
    protocol: 'udp'
    domain: 'ip'

  - type: 'accept'
    filename: 'vmnet'
    name: 'vmnet'
    table: 'filter'
    chain: 'FORWARD'
    domain: 'ip'
    interface_present: 'tun0'
    outerface_present: 'virbr0'
    comment: 'Forward traffic from OpenVPN to VMs'

  - type: 'accept'
    filename: 'vmnet_public'
    name: 'vmnet_public'
    table: 'filter'
    chain: 'FORWARD'
    domain: 'ip'
    interface_present: 'virbr0'
    saddr: '192.168.122.0/24'
    comment: 'Forward traffic from VMs to the internet'

  - type: 'custom'
    filename: 'vmnet_nat'
    name: 'vmnet_nat'
    comment: 'Perform NAT for VMs'
    rules: |
      domain ip table nat chain POSTROUTING {
        outerface enp0s20f0 {
          MASQUERADE;
        }
      }
