---

ferm__host_rules:
  - type: 'accept'
    filename: 'haproxy'
    name: 'haproxy'
    table: 'filter'
    chain: 'INPUT'
    dport: [ 80, 443 ]
    protocol: 'tcp'
    domain: 'ip'

  - type: 'accept'
    filename: 'openvpn'
    name: 'openvpn'
    table: 'filter'
    chain: 'INPUT'
    dport: [ 1194 ]
    protocol: 'udp'
    domain: 'ip'

  - type: 'accept'
    filename: 'vmnet'
    name: 'vmnet'
    table: 'filter'
    chain: 'FORWARD'
    domain: 'ip'
    interface_present: 'tun0'
    outerface_present: 'virbr0'
    comment: 'Forward traffic from OpenVPN to VMs'

  - type: 'accept'
    filename: 'devnet'
    name: 'devnet'
    table: 'filter'
    chain: 'FORWARD'
    domain: 'ip'
    interface_present: 'tun0'
    outerface_present: 'virbr1'
    comment: 'Forward traffic from OpenVPN to devnet VMs'

  - type: 'accept'
    filename: 'vmnet_public'
    name: 'vmnet_public'
    table: 'filter'
    chain: 'FORWARD'
    domain: 'ip'
    interface_present: 'virbr0'
    saddr: '192.168.122.0/24'
    comment: 'Forward traffic from VMs to the internet'

  - type: 'accept'
    filename: 'devnet_public'
    name: 'devnet_public'
    table: 'filter'
    chain: 'FORWARD'
    domain: 'ip'
    interface_present: 'virbr1'
    saddr: '192.168.199.0/24'
    comment: 'Forward traffic from devnet VMs to the internet'

  - type: 'custom'
    filename: 'vmnet_nat'
    name: 'vmnet_nat'
    comment: 'Perform NAT for VMs'
    rules: |
      domain ip table nat chain POSTROUTING {
        outerface enp0s20f0 {
          MASQUERADE;
        }
      }

  - type: 'accept'
    filename: 'prosody_forward'
    name: 'prosody_forward'
    table: 'filter'
    chain: 'FORWARD'
    domain: 'ip'
    state: 'NEW'
    dport: [ 5222 ]

  - type: 'custom'
    filename: 'prosody_nat'
    name: 'prosody_nat'
    rules: |
      domain ip table nat chain PREROUTING {
        protocol tcp dport 5222 {
          DNAT to {{ prosody__private_ip }}:5222;
        }
      }
