---

synapse__repositories: 'main prerelease'

synapse__keyring__dependent_apt_keys:
  - id: AAF9AE843A7584B5A3E4CD2BCF45A512DE2DA058
    url: 'https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg'
    repo: 'deb https://packages.matrix.org/debian/ {{ ansible_distribution_release }} {{ synapse__repositories }}'
    state: 'present'

synapse__port: 8008

synapse__bind_addresses: ['127.0.0.1']

synapse__metrics_port: 9666

synapse__metrics_bind_addresses: ['127.0.0.1']

synapse__user_ips_max_age: '1d'

synapse__max_upload_size: '10M'

synapse__database: 'synapse'
synapse__database_user: 'synapse'
synapse__database_password: ''
synapse__database_host: '127.0.0.1'

synapse__enable_registration: 'false'
synapse__enable_3pid_lookup: 'false'

synapse__enable_presence: 'false'

synapse__enable_device_name_over_federation: 'false'

synapse__caches_expiry_time: '60m'

synapse__enable_phonehome_stats: 'false'

synapse__remote_media_lifetime: '1d'

synapse__token_registration: 'true'
