---

- file:
    path: /etc/httpd/
    state: directory
    mode: 0755
    owner: root
    group: wheel

- copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: wheel
  with_items:
    - { src: "httpd.conf", dest: "/etc/httpd.conf" }
    - { src: "httpd/", dest: "/etc/httpd" }
  notify: Restart httpd

- lineinfile:
    path: /etc/httpd.conf
    line: 'include "/etc/httpd/{{ item }}.conf"'
  with_items:
      - capitalism
      - hacked
      - erethon
  notify: Restart httpd
