---

- name: Create /etc/httpd/
  file:
    path: /etc/httpd/
    state: directory
    mode: 0755
    owner: root
    group: wheel

- name: Copy httpd config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: wheel
    mode: "{{ item.mode }}"
  with_items:
    - { src: "httpd.conf", dest: "/etc/httpd.conf", mode: "0644" }
    - { src: "httpd/", dest: "/etc/httpd", mode: "0755"}
  notify: Restart httpd

- name: Add individual sites
  lineinfile:
    path: /etc/httpd.conf
    line: 'include "/etc/httpd/{{ item }}.conf"'
  with_items:
    - capitalism
    - hacked
    - erethon
    - blog
    - about.erethon.com
    - git.erethon.com
    - dgrig.com
  notify: Restart httpd
