---

- name: Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    restart_policy: always
    pull: true
    ports:
      - "127.0.0.1:{{ haproxy__grafana_backend_port }}:3000"
    volumes:
      - "{{ grafana__volume }}:/var/lib/grafana"
    links:
      - "{{ influxdb__name}}:influx"
    env:
      GF_SECURITY_ADMIN_USER="{{ grafana__admin_user }}"
      GF_SECURITY_ADMIN_PASSWORD="{{ grafana__admin_password }}"
