---

- name: Download Element GPG key
  get_url:
    url: "{{ element__signing_key }}"
    dest: /tmp/riot-release-key.asc

- name: Import Element GPG key
  shell: gpg --import /tmp/riot-release-key.asc

- name: Download Element release
  get_url:
    url: "{{ element__release_url }}"
    dest: /tmp/
    checksum: "sha512:{{ element__release_checksum }}"

- name: Download Element signature file
  get_url:
    url: "{{ element__release_signature_url }}"
    dest: /tmp/

- name: Verify Element release with signature file
  shell: "gpg --verify /tmp/element-v{{ element__release_version }}.tar.gz.asc /tmp/element-v{{ element__release_version }}.tar.gz"

- name: Extract and deploy Element to the webserver directory
  unarchive:
    src: /tmp/element-v{{ element__release_version }}.tar.gz
    dest: "{{ element__deploy_directory }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Configure Element
  template:
    src: config.json
    dest: "{{ element__deploy_directory }}/config.json"
  tags: ["riot::configure"]
