---

- name: f.erethon.com nginx docker
  docker:
    name: f.erethon.com
    image: nginx
    state: restarted
    restart_policy: always
    pull: always
    ports:
    - 127.0.0.1:18081:80
    volumes:
    - /data/volumes/files:/usr/share/nginx/html:ro
    - /data/volumes/files/nginx.conf:/etc/nginx/nginx.conf:ro
