---

- name: f.erethon.com nginx docker
  docker_container:
    name: f.erethon.com
    image: nginx
    state: started
    restart_policy: always
    pull: true
    ports:
    - "{{ files__private_ip }}:{{ files__port }}:80"
    volumes:
    - "{{ docker__volumes_location }}/f.erethon.com:/usr/share/nginx/html:ro"
