---

- name: Manage Synapse server (Matrix)
  hosts: [ 'synapse' ]
  become: True

  collections: [ 'debops.debops', 'debops.roles01',
                'debops.roles02', 'debops.roles03' ]

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: secret

    - role: cron
      tags: [ 'role::cron', 'skip::cron' ]

    - role: keyring
      tags: [ 'role::keyring', 'skip::keyring', 'role::nginx' ]
      keyring__dependent_apt_keys:
        - '{{ synapse__keyring__dependent_apt_keys }}'

    - role: synapse
      tags: [ 'role::synapse']
