---

- file:
    path: "{{ influxdb__volume }}/etc/"
    owner: root
    group: root
    state: directory

- template:
    src: influxdb.conf.j2
    dest: "{{ influxdb__volume }}/etc/influxdb.conf"
    owner: root
    group: root

- copy:
    src: collectd_types.db
    dest: "{{ influxdb__volume }}/etc/collectd_types.db"

- name: InfluxDB container
  docker_container:
    name: "{{ influxdb__name }}"
    image: influxdb
    state: started
    restart_policy: always
    pull: true
    ports:
      - "{{ influxdb__tinc_ip }}:25826:25826/udp"
    volumes:
      - "{{ influxdb__volume }}/data:/var/lib/influxdb"
      - "{{ influxdb__volume }}/etc/:/etc/influxdb"
    env:
      INFLUXDB_DB="{{ influxdb__collectd_db }}"
      INFLUXDB_ADMIN_ENABLED=true
      INFLUXDB_ADMIN_USER="{{ influxdb__admin_user }}"
      INFLUXDB_ADMIN_USER_PASSWORD="{{ influxdb__admin_password }}"
      INFLUXDB_USER="{{ influxdb__user }}"
      INFLUXDB_USER_PASSWORD="{{ influxdb__user_password }}"
