---

- name: Copy installurl
  copy:
    src: installurl
    dest: /etc/installurl

- name: Install packages
  openbsd_pkg:
    name: "{{ openbsd__packages }}"
    state: present

- name: Create groups
  group:
    name: "{{ item.group | d(item.name) }}"
  with_flattened:
  - "{{ users__accounts }}"

- name: Create management user
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    state: "{{ item.state }}"
    append: "{{ item.append }}"
    shell: "{{ item.openbsdshell }}"
  with_items:
  - "{{ users__accounts }}"

- authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.sshkeys[0] }}"
  with_items:
  - "{{ users__accounts }}"
