---

apt_install__packages: [git, vim, rxvt-unicode-256color, screen, tmux,
    fail2ban, mlocate, htop, sudo, ferm, strace, ltrace, file, monit, less,
    nmon, colordiff, bash-completion, telnet, dstat, ca-certificates, curl,
    sysstat, tcpdump, zsh, mosh, lsof, iotop, netcat, mtr-tiny, bwm-ng,
    etckeeper,prometheus-node-exporter]
