---

ferm__enabled: True
ferm__filter_icmp: False
ferm__filter_syn: False
ferm__filter_recent: False

ferm__rules:
  - name: 'node_exporter'
    type: 'accept'
    filename: 'node_exporter'
    table: 'filter'
    chain: 'INPUT'
    dport: [ 9100 ]
    saddr: "{% if hostvars['prometheus_host'] is defined %} {{ hostvars['prometheus_host'].ansible_host }} {% else %} '127.0.0.1' {% endif %}"
    protocol: 'tcp'
    domain: 'ip'
