---

users__enabled: True

users__dotfiles_enabled: True
users__dotfiles_name: 'erethon'

users__dotfiles_default_map:
  'erethon':
    repo: 'https://github.com/erethon/dotfiles.git'

users__accounts:
  - name: 'tsironis'
    state: present
    group: 'tsironis'
    groups: ['admins']
    append: True
    gid: 1005
    uid: 1005
    shell: '/usr/bin/zsh'
    openbsdshell: '/usr/local/bin/zsh'
    sshkeys: [ 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIuwVLDASGrbHpw49LWj4hIwG2SCiaYaUVxqyzIk5LU0pmzfLSPfbwhs88IKqtz3V2TopqdlveLhLSeSlwIsyd+XddsvFmcwOojxzdD508DahVnrb/twCQQ2eU/Y9achNqUjjz2aqG/xfxPzCUn5NeZSb84gXxe3jRqN0dZc+TS5i6hsGGYwrZER9tjeXYuRD9867+rvUDJ8XybwQ9UG6yDc6fDyri5AoJcWYZ/YYXPM1qswTgpcwY6vktSDShgb4ORvOROEOoa9N+h1G9zu4bEz/egq+brZ/beRbtHTxsMD4bHD3vdad6eXRDLZU74xFq84WydcBuonYIfqWZGQFuoszjtWxxaShi4qswLExEMnNZmIGNJgI4myTitihj4avllleDM0kVkpcrWI0/lsUy/a8HLpURijzzfRhusxRevTijtb9dMvPNPb+YsKs/G44OvLxKAuf8ZyfL+Zdnu/oJkJCblSjPYKV77KV8vUE8Z6BMcMxhMPrs4e5N+qJbPxwxLq8/quFFLZnpXlTaDDa3JONJ7r60TGhXIIAjEYcx3uw3lYIk0T01wdRQKhuKt0yNHT2u2cYkb21eEKpCvC6U6a6fvU7JrMO0iYRC5RE+KCgiggcoYPvak62BFiHLUB5yw6wEPQ9wb1p+shnPkBDPsOilDafEB8/XifSL7r83Mw== tsironis.dimitris@gmail.com' ]
