---

element__signing_key: https://packages.riot.im/element-release-key.asc

element__release_version: "1.7.34"

element__release_checksum: "96bc96d98677e7154790accd7fca8314aada7352d8b8c1a9cc1b18c65b78705db766e5238feda6a3601aabd1f487b115dbaaecd0f55354b752ea07730e2d2312"

element__release_url: "https://github.com/vector-im/element-web/releases/download/v{{ element__release_version }}/element-v{{ element__release_version }}.tar.gz"

element__release_signature_url: "https://github.com/vector-im/element-web/releases/download/v{{ element__release_version }}/element-v{{ element__release_version }}.tar.gz.asc"

element__deploy_directory: ""

element__matrix_homeserver: "https://matrix.org"

element__matrix_server_name: "matrix.org"

element__matrix_identity_server: "https://vector.im"

element__brand: "Element"

element__jitsi_url: "jitsi.modular.im"
