---

element__signing_key: https://packages.riot.im/element-release-key.asc

element__release_version: "1.10.6"

element__release_checksum: "3ef064e81c03727aaaf0a1f4fb7c787b638868a7cda9a6b00e287eda8b26fd94e11d634be8b29e2c0d563d462a8253667166b6e0181483f8b8296cbcf800ba3a"

element__release_url: "https://github.com/vector-im/element-web/releases/download/v{{ element__release_version }}/element-v{{ element__release_version }}.tar.gz"

element__release_signature_url: "https://github.com/vector-im/element-web/releases/download/v{{ element__release_version }}/element-v{{ element__release_version }}.tar.gz.asc"

element__deploy_directory: ""

element__matrix_homeserver: "https://matrix.org"

element__matrix_server_name: "matrix.org"

element__matrix_identity_server: "https://vector.im"

element__brand: "Element"

element__jitsi_url: "jitsi.modular.im"

element__enable_labs: "true"

element__enable_widgets: "false"
