---

element__signing_key: https://packages.riot.im/element-release-key.asc

element__release_version: "1.10.10"

element__release_checksum: "dc7ab99d93c0aae71806b176340663a5f59cddc4b00ac7ed423a689f28d812db472398f75d1e0787a2a666ac9121544e1aba41d8550f9dc34b583d852eb74dad"

element__release_url: "https://github.com/vector-im/element-web/releases/download/v{{ element__release_version }}/element-v{{ element__release_version }}.tar.gz"

element__release_signature_url: "https://github.com/vector-im/element-web/releases/download/v{{ element__release_version }}/element-v{{ element__release_version }}.tar.gz.asc"

element__deploy_directory: ""

element__matrix_homeserver: "https://matrix.org"

element__matrix_server_name: "matrix.org"

element__matrix_identity_server: "https://vector.im"

element__brand: "Element"

element__jitsi_url: "jitsi.modular.im"

element__enable_labs: "true"

element__enable_widgets: "false"
element__enable_feedback: "false"
element__enable_identity: "false"
element__enable_thirdpartyid: "false"
element__enable_social: "false"
