---

- name: erethon.com nginx docker
  docker:
    name: erethon.com
    image: nginx
    state: restarted
    restart_policy: always
    pull: always
    ports:
    - 127.0.0.1:18083:80
    volumes:
    - /data/volumes/erethon.com:/usr/share/nginx/html:ro
    - /data/volumes/erethon.com/nginx.conf:/etc/nginx/nginx.conf:ro
