---

nginx_acme: False
nginx_http_extra_options: 'limit_req_zone $binary_remote_addr zone=cgilimit:10m rate=5r/s;'
nginx__servers:
  - name: erethon.com
    listen:
      - "{{ ansible_host }}:80"
    redirect_to_ssl: False
    acme: False
  - name: blog.erethon.com
    listen:
      - "{{ ansible_host }}:80"
    redirect_to_ssl: False
    acme: False
    location:
      '/': 'try_files $uri $uri/ $uri.html $uri.htm /index.html /index.htm =404;'
      '~ ^/about/?$': 'return 302 https://about.erethon.com;'
  - name: about.erethon.com
    listen:
      - "{{ ansible_host }}:80"
    redirect_to_ssl: False
    acme: False
  - name: f.erethon.com
    listen:
      - "{{ ansible_host }}:80"
    redirect_to_ssl: False
    acme: False
  - name: hacked.erethon.com
    listen:
      - "{{ ansible_host }}:80"
    redirect_to_ssl: False
    acme: False
  - name: sv1tbt.gr
    listen:
      - "{{ ansible_host }}:80"
    redirect_to_ssl: False
    acme: False
  - name: dgrig.com
    listen:
      - "{{ ansible_host }}:80"
    redirect_to_ssl: False
    acme: False
  - name: qr.erethon.com
    listen:
      - "{{ ansible_host }}:80"
    redirect_to_ssl: False
    acme: False
  - name: workwithme.erethon.com
    listen:
      - "{{ ansible_host }}:80"
    redirect_to_ssl: False
    acme: False
  - name: rnode-flasher.erethon.com
    listen:
      - "{{ ansible_host }}:80"
    redirect_to_ssl: False
    acme: False
  - name: tz.erethon.com
    listen:
      - "{{ ansible_host }}:80"
    redirect_to_ssl: False
    location:
      '/': |
        limit_req zone=cgilimit burst=5 nodelay;
        limit_req_status 429;
        root /srv/www/sites/tz.erethon.com/public;
        include fastcgi_params;
        fastcgi_pass unix:/var/run/fcgiwrap.socket;
        fastcgi_param SCRIPT_FILENAME /srv/www/sites/tz.erethon.com/public/tz-cgi.sh;
    acme: False
